/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as AppLayoutIndexRouteImport } from './routes/_app-layout/index'
import { Route as AppLayoutListingIndexRouteImport } from './routes/_app-layout/listing/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutListingIndexRoute = AppLayoutListingIndexRouteImport.update({
  id: '/listing/',
  path: '/listing/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/listing/': typeof AppLayoutListingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/listing': typeof AppLayoutListingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/_app-layout/': typeof AppLayoutIndexRoute
  '/_app-layout/listing/': typeof AppLayoutListingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/listing/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/listing'
  id: '__root__' | '/_app-layout' | '/_app-layout/' | '/_app-layout/listing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/': {
      id: '/_app-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/listing/': {
      id: '/_app-layout/listing/'
      path: '/listing'
      fullPath: '/listing/'
      preLoaderRoute: typeof AppLayoutListingIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutListingIndexRoute: typeof AppLayoutListingIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutListingIndexRoute: AppLayoutListingIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
