/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as AppLayoutIndexRouteImport } from './routes/_app-layout/index'
import { Route as AppLayoutListingsIndexRouteImport } from './routes/_app-layout/listings/index'
import { Route as AppLayoutListingsListingsVehiclesRouteImport } from './routes/_app-layout/listings/_listings.vehicles'
import { Route as AppLayoutListingsListingsUsersRouteImport } from './routes/_app-layout/listings/_listings.users'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutListingsIndexRoute = AppLayoutListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutListingsListingsVehiclesRoute =
  AppLayoutListingsListingsVehiclesRouteImport.update({
    id: '/listings/_listings/vehicles',
    path: '/listings/vehicles',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutListingsListingsUsersRoute =
  AppLayoutListingsListingsUsersRouteImport.update({
    id: '/listings/_listings/users',
    path: '/listings/users',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/listings/': typeof AppLayoutListingsIndexRoute
  '/listings/users': typeof AppLayoutListingsListingsUsersRoute
  '/listings/vehicles': typeof AppLayoutListingsListingsVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/listings': typeof AppLayoutListingsIndexRoute
  '/listings/users': typeof AppLayoutListingsListingsUsersRoute
  '/listings/vehicles': typeof AppLayoutListingsListingsVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/_app-layout/': typeof AppLayoutIndexRoute
  '/_app-layout/listings/': typeof AppLayoutListingsIndexRoute
  '/_app-layout/listings/_listings/users': typeof AppLayoutListingsListingsUsersRoute
  '/_app-layout/listings/_listings/vehicles': typeof AppLayoutListingsListingsVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/listings/' | '/listings/users' | '/listings/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/listings' | '/listings/users' | '/listings/vehicles'
  id:
    | '__root__'
    | '/_app-layout'
    | '/_app-layout/'
    | '/_app-layout/listings/'
    | '/_app-layout/listings/_listings/users'
    | '/_app-layout/listings/_listings/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/': {
      id: '/_app-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/listings/': {
      id: '/_app-layout/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AppLayoutListingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/listings/_listings/vehicles': {
      id: '/_app-layout/listings/_listings/vehicles'
      path: '/listings/vehicles'
      fullPath: '/listings/vehicles'
      preLoaderRoute: typeof AppLayoutListingsListingsVehiclesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/listings/_listings/users': {
      id: '/_app-layout/listings/_listings/users'
      path: '/listings/users'
      fullPath: '/listings/users'
      preLoaderRoute: typeof AppLayoutListingsListingsUsersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutListingsIndexRoute: typeof AppLayoutListingsIndexRoute
  AppLayoutListingsListingsUsersRoute: typeof AppLayoutListingsListingsUsersRoute
  AppLayoutListingsListingsVehiclesRoute: typeof AppLayoutListingsListingsVehiclesRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutListingsIndexRoute: AppLayoutListingsIndexRoute,
  AppLayoutListingsListingsUsersRoute: AppLayoutListingsListingsUsersRoute,
  AppLayoutListingsListingsVehiclesRoute:
    AppLayoutListingsListingsVehiclesRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
